on:
  push:
    branches:
      - main
  pull_request:

name: Continuous Integration
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add rustup components
        run: rustup component add rustfmt && rustup component add clippy
      - name: Setup build cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --profile=ci --all-features --no-run --locked
      # TODO: Make tests runnable in CI
      # - name: Test
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --profile=ci --all-features
      - name: Deny all clippy warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --profile=ci --all-features --tests
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
